# Generated by Django 3.2.21 on 2023-09-21 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ref_text', models.CharField(max_length=10)),
                ('dispensing_size', models.CharField(max_length=20)),
                ('indication', models.TextField()),
                ('dosage', models.CharField(max_length=50)),
                ('precautions', models.TextField()),
                ('preferred_use', models.CharField(max_length=20)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
